version: 0.2
env:
  secrets-manager:
    DOCKERHUB_PASS: "DockerLogin:DOCKER_P"
    DOCKERHUB_USERNAME: "DockerLogin:DOCKER_U"
    db_host: "DBSInfo:host"
    db_user: "DBSInfo:username"
    db_password: "DBSInfo:password"
    db_port: "DBSInfo:port"
    db_database: "DBSInfo:dbname"
phases:
  pre_build:
    on-failure: CONTINUE
    commands:
      - cd frontend
      - npm install
      - npm test
  build:
    commands:
      - cd ..
      - echo Building impactnginx, impactfrontend, and impactbackend images
      - docker build -t ardiank/impactnginx -f ./nginx/Dockerfile ./nginx
      - cd frontend && docker build -t ardiank/impactfrontend .
      - cd ../backend && docker build -t ardiank/impactbackend -f Dockerfile .
      - echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
  post_build:
    commands:
      - echo Pushing images to Docker Hub
      - docker push ardiank/impactnginx
      - docker push ardiank/impactfrontend
      - docker push ardiank/impactbackend