version: '3.3'
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  client:
      build: 
        context: ./frontend
        dockerfile: Dockerfile
      #ports:
      #   - "5000:5000"
      container_name: frontend

  # backend:
  #     build: 
  #       context: ./backend
  #       dockerfile: Dockerfile
  #     #ports:
  #     #  - "3000:3000"
  #     container_name: backend